import Image from 'next/image';
import Link from 'next/link';
import React from 'react'
import { FaGithub, FaShareSquare } from 'react-icons/fa';

const ProjectSection = () => {
   const backgroundColor =
    "bg-gradient-to-r from-[#DBE7F6] via-[#D6DFEF] to-[#E6DCEF] p-4";

    const myProjects = [
        {
            title: "Ai Room Designer",
            description: "AI powered room designer which transforms user's image into redesigned image generated by AI",
            technologies: ["Next.js", "PostgreSql", "Tailwind Css", "Firebase Storage", "Drizzle-orm", "Paypal", "Auth"],
            imageUrl: "/project-roomDesigner.png",
            projectLink: "https://ai-room-designer-five.vercel.app/",
            gitHubLink: "https://github.com/Sharad10-10/AI-Room-Designer"

        },
        {
            title: "User-Product Dashboard",
            description: "Fullstack Nextjs user and products management dashboard app with user name and password authentication",
            technologies: ["Next.js", "Javascript", "MongoDB", "Tailwind Css", "NextAuth.js", "bcrypt" ],
            imageUrl: "/project-dashboard.png",
            projectLink: "https://product-user-dashboard.vercel.app/",
             gitHubLink: "https://github.com/Sharad10-10/product-user-dashboard"
        },
        {
             title: "Little Lemon Restaurant",
            description: "A frontend React restaurant project with clean interactive UI with feature of table reservation and proper form validation.",
            technologies: ["React", "Javascript", "Tailwind Css", "Formik", "Yup"],
            imageUrl: "/project-littleLemon.png",
            projectLink: "https://little-lemon-kappa-ochre.vercel.app/",
             gitHubLink: "https://github.com/Sharad10-10/little-lemon"
        },
        {
            title: "Dice Game",
            description: "A fun and interactive dice game built with React where users guess the outcome of dice rolls to score points!",
            technologies: ["React", "Javascript", "Styled Component"],
            imageUrl: "/project-dice.png",
            projectLink: "https://dice-game-peach-eta.vercel.app/",
             gitHubLink: "https://github.com/Sharad10-10/Dice-Game"
        }
    ]


  return (
    <div className={`flex flex-col gap-12 items-center justify-center ${backgroundColor} pt-12`}>
       <div>
             <div className='text-center flex flex-col gap-2'>
                <h1 className='text-4xl'>Featured Projects</h1>
                <h2 className='text-[#707786]'>A section of my works</h2>
            </div>
       </div>

    <div className='flex gap-12 flex-wrap justify-center items-center'>

             {myProjects.map((projects, index)=>{
        return (
              <div key={index} className='h-140 max-w-120 w-full bg-white rounded-xl overflow-hidden hover:scale-105 transition-all duration-500 hover:shadow-2xl'>
            <div className='flex items-center bg-[#F2F7FF] px-4 py-2 border-b border-gray-700/10'>

                 <div className="flex gap-2">
                    <div className="h-3 w-3 bg-[#F04242] rounded-full hover:scale-110 transition-all"></div>
                    <div className="h-3 w-3 bg-[#FBBD23] rounded-full hover:scale-110 transition-all"></div>
                    <div className="h-3 w-3 bg-[#26D968] rounded-full hover:scale-110 transition-all"></div>
                </div>

                <div className='text-center text-[#707786] flex-1'>
                    <h1>{projects.title}.app</h1>
                </div>
            </div>

            <div>
    
                <div className='w-full overflow-hidden'>
                    <Image className='w-full h-60 object-cover' src={projects.imageUrl} width={800} height={200} alt='project-dice'/>
                </div>

                <div className='p-4 pb-8 flex flex-col gap-4 '>
                    {/* desc */}
                    <h1 className='text-xl font-medium'>{projects.title}</h1>
                    <h2 className='text-[#707786] text-md'>{projects.description}</h2>
                    <div className='flex gap-2 flex-wrap'>
                      {projects?.technologies?.map((tech, index)=> {
                        return(
                            <div key={index}><p className='bg-[#E9EAED] rounded-4xl px-3 font-medium'>{tech}</p></div>
                        )
                      })}
                       
                    </div>
                    
                    <div className='border border-black/10'></div>

                    <div className='flex gap-8 text-lg text-[#53575F] '>
                       <Link href={projects.gitHubLink}><FaGithub className='cursor-pointer hover:scale-105 transition-all' />Github</Link>
                       <Link href={projects.projectLink}><FaShareSquare className='cursor-pointer hover:scale-105 transition-all'/>Live Demo</Link>

                    </div>  
                </div>
            </div>


            
        </div>

        )
     })}


    </div>
    </div>
  )
}

export default ProjectSection